language: generic
sudo: required
services:
  - docker
env:
  global:
    - secure: "qI0QEOmT3P3x9MfWwY0F43CxV8MRvuYDUtGRXIXs1Utpk/1wJv4zsebyHabuusEai9QakRo1kexwAuAcbyeiFTXKwn8DKIId2BDx14/fzmHSsyj86W1Tao5HAoD4NDQReI+c3LX5ipDtInlBXip0NgMMmQiT4+IzVkf9itAewCg="
script:
  - openssl aes-256-cbc -K "$encrypted_1536cf00117f_key" -iv "$encrypted_1536cf00117f_iv" -in deploy_key.enc -out deploy_key -d
  - cd .. &&
    git clone https://github.com/whatwg/wattsi.git wattsi &&
    git clone https://github.com/whatwg/html-build.git html-build
  - cp html/Dockerfile . &&
    echo "**/.git" > .dockerignore &&
    docker pull whatwg/html-deploy:latest &&
    docker build --cache-from whatwg/html-deploy:latest
                 --tag whatwg/html-deploy:latest
                 --build-arg "travis_pull_request=$TRAVIS_PULL_REQUEST"
                 . &&
    docker run --volume "$(pwd)/html":/whatwg/html whatwg/html-deploy:latest
  - docker tag whatwg/html-deploy:latest "whatwg/html-deploy:$TRAVIS_BUILD_NUMBER" &&
    docker login -u domenicdenicola -p $DOCKER_PASSWORD &&
    docker push whatwg/html-deploy
branches:
  only:
    - master
notifications:
  email:
    on_success: never
    on_failure: always
